#!/usr/bin/env python3
"""Installed entrypoint for the JUNCA public-testnet validator."""

from jaios.social_ecosystem_chain import validator_node
from jaios.social_ecosystem_chain.validator_liveness import (
    RecoveringBoundedFinalityLoop,
)

validator_node.BoundedFinalityLoop = RecoveringBoundedFinalityLoop

raise SystemExit(validator_node.main())
